language: generic
services:
- docker
matrix:
  include:
  - os: linux
    dist: trusty
    env:
    - DEPLOY_FILENAME=Bottle_Linux.tar.gz
    - DEPLOY_DIR=bin/linux
    - DEPLOY_STATIC="--static"
  - os: osx
    env:
    - DEPLOY_FILENAME=Bottle_macOS.tar.gz
    - DEPLOY_DIR=bin/darwin
    - DEPLOY_STATIC=""
install:
- chmod +x bin/ci
- bin/ci prepare_build
script:
- bin/ci build
after_success:
- bin/ci deploy
deploy:
  provider: releases
  api_key:
    secure: ""
  file: "$DEPLOY_FILENAME"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: 73686f77/bottle.cr