name: Continuous Delivery

on: 
  release:
    types:
      - created

jobs:
  linux:
    name: Continuous Delivery - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
        - ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - name: Actions - Use CheckOut@V2
      uses: actions/checkout@v2
    - name: Install - Apt-Get Update
      run: apt-get update
    - name: Install - Apt-Get Upgrade
      run: apt-get -y upgrade
    - name: Install - Apt-Get Dependencies
      run: apt-get install openssl libreadline-dev -y
    - name: Install - Bottle Dependencies
      run: shards install
    - name: Test - Crystal Spec
      run: crystal spec --error-trace --stats --progress --no-debug
    - name: Deploy - Create Directory
      run: mkdir -p bin/linux
    - name: Deploy - Bottle Build
      run: crystal build src/bottle.cr -s --release --no-debug -o bin/linux/bottle
    - name: Deploy - Create Archive
      run: tar -cvzf Bottle_Linux.tar.gz bin/linux/bottle
    - name: Actions - Upload Release
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Bottle_Linux.tar.gz
        asset_name: Bottle_Linux.tar.gz
        asset_content_type: application/x-gzip

  macOS:
    name: Continuous Delivery - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
        - macOS-latest
    steps:
    - name: Actions - Use CheckOut@V2
      uses: actions/checkout@v2
    - name: Install - Brew Package Management
      run: brew update
    - name: Install - Crystal Language
      run: brew install crystal
    - name: Install - Bottle Dependencies
      run: shards install
    - name: Test - Crystal Spec
      run: crystal spec --error-trace --stats --progress --no-debug
    - name: Deploy - Create Directory
      run: mkdir -p bin/darwin
    - name: Deploy - Bottle Build
      run: crystal build src/bottle.cr -s --no-debug -o bin/darwin/bottle
    - name: Deploy - Create Archive
      run: tar -cvzf Bottle_macOS.tar.gz bin/darwin/bottle
    - name: Actions - Upload Release
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Bottle_macOS.tar.gz
        asset_name: Bottle_macOS.tar.gz
        asset_content_type: application/x-gzip
